# Default build settings
[build]
  publish = "dist"
  command = "npm run generate"

# Production context
[context.production]
  command = "npm run generate"

# Redirect rules for subdomains
[[redirects]]
  from = "https://semmverse.bagumamartin.com/*"
  to = "/semmverse/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://bodysync.bagumamartin.com/*"
  to = "/bodysync/:splat"
  status = 200
  force = true

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"